name: DevStoneCutter
version: '${version}'
main: com.teenkung.devstonecutter.DevStoneCutter
api-version: 1.19
depend: [ItemsAdder, NBTAPI]
commands:
  stonecutter:
    permission: DevStoneCutter.admin
